//! CPU PJRT plugin selection.
//!
//! This is the Rust adaptation of ZML's `platforms/cpu` loader. The common
//! PJRT object model lives in `nml_pjrt`; this crate owns only CPU enablement,
//! Bazel runfiles resolution, and trust in the pinned CPU plugin artifact.

use nml_pjrt::Plugin;
use runfiles::Runfiles;
use std::error::Error as StdError;
use std::fmt;

const CPU_PLUGIN_RLOCATION: &str = env!("NML_CPU_PJRT_RLOCATION");

#[derive(Debug)]
pub enum LoadError {
    Unavailable,
    Runfiles(String),
    MissingRunfile(String),
    Pjrt(nml_pjrt::Error),
}

impl fmt::Display for LoadError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unavailable => {
                f.write_str("the CPU PJRT backend is disabled in this Bazel configuration")
            }
            Self::Runfiles(message) => write!(f, "failed to initialize Bazel runfiles: {message}"),
            Self::MissingRunfile(path) => {
                write!(f, "CPU PJRT plugin is absent from Bazel runfiles: {path}")
            }
            Self::Pjrt(error) => error.fmt(f),
        }
    }
}

impl StdError for LoadError {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match self {
            Self::Pjrt(error) => Some(error),
            _ => None,
        }
    }
}

impl From<nml_pjrt::Error> for LoadError {
    fn from(error: nml_pjrt::Error) -> Self {
        Self::Pjrt(error)
    }
}

pub fn is_enabled() -> bool {
    !CPU_PLUGIN_RLOCATION.is_empty()
}

/// Loads the CPU plugin selected for the current supported host.
pub fn load() -> Result<Plugin, LoadError> {
    if !is_enabled() {
        return Err(LoadError::Unavailable);
    }

    let runfiles = Runfiles::create().map_err(|error| LoadError::Runfiles(error.to_string()))?;
    let path = runfiles::rlocation!(runfiles, CPU_PLUGIN_RLOCATION)
        .ok_or_else(|| LoadError::MissingRunfile(CPU_PLUGIN_RLOCATION.to_owned()))?;

    // SAFETY: this rlocation is generated by Bazel from the exact CPU archive
    // selected in platforms/cpu/cpu.bzl, whose URL and digest are pinned. User
    // input cannot substitute an arbitrary shared library here.
    unsafe { Plugin::load_trusted(path) }.map_err(LoadError::from)
}
